os: linux 
arch: arm64 
dist: bionic

services:
    - docker

stages:
    - build_publish

before_script:
    - mix deps.get

env:
    global:
        - MIX_ENV=prod
jobs:
    include:
        - stage: build_publish
          script:
            - echo "$DOCKER_PASSWORD" | docker login registry.gitlab.com -u "$DOCKER_USERNAME" --password-stdin
            - docker build -t registry.gitlab.com/larsdebruijn/coffeetime:latest .
            - docker push registry.gitlab.com/larsdebruijn/coffeetime:latest
