os: linux 
arch: arm32 
dist: bionic

services:
    - docker

stages:
    - build_publish

jobs:
    include:
        - stage: build_publish
          script:
            - echo "$DOCKER_PASSWORD" | docker login registry.gitlab.com -u "$DOCKER_USERNAME" --password-stdin
            - docker build -t registry.gitlab.com/larsdebruijn/coffeetime:latest .
            - docker push registry.gitlab.com/larsdebruijn/coffeetime:latest
