# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.registryPassword }} | docker login -u ${{ secrets.registryUsername }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag larsdebruijn/coffeetime:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push larsdebruijn/coffeetime:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
    - uses: uraimo/run-on-arch-action@v1.0.8
      id: docker-build
      with:
        architecture: armv7
        distribution: ubuntu18.04
        run: |
          docker build . --file Dockerfile --tag larsdebruijn/coffeetime:latest
          docker push larsdebruijn/coffeetime:latest
